# HOMEPAGE ROUTES
homepage:
    path:   '/home'
    defaults:  { _controller: AppBundle:Home:home}

alt_homepage:
    path:   '/'
    defaults: { _controller: AppBundle:Home:home}

# user management routes
users:
  path: '/users'
  defaults: {_controller: AppBundle:Users:users}

user_edit:
  path: '/user_edit'
  defaults: {_controller: AppBundle:Users:edit}

# course routes
courses:
  path: '/courses'
  defaults: {_controller: AppBundle:Course:courses}
  methods: [GET]

course_edit:
  path: '/course/edit/{courseId}'
  defaults:
    _controller: AppBundle:Course:editCourse
    courseId: 0
  methods: [GET]

course_delete:
  path: '/course/delete/{courseId}'
  defaults: {_controller: AppBundle:Course:deleteCourse}
  methods: [GET]

course_modify:
  path: '/modify/course'
  defaults: {_controller: AppBundle:Course:modifyPost}
  methods: [POST]

# section routes
submission_search:
  path: '/submission_search'
  defaults:
    _controller: AppBundle:Section:searchSubmissions
  methods: [POST]

section_edit:
  path: '/section/edit/{sectionId}'
  defaults:
    _controller: AppBundle:Section:editSection
    sectionId: 0
  methods: [GET]

section_delete:
  path: '/section/delete/{sectionId}'
  defaults: {_controller: AppBundle:Section:deleteSection}
  methods: [GET]
  
section_clone:
  path: '/section/clone/{sectionId}/semester/{semester}/year/{year}'
  defaults: {_controller: AppBundle:Section:cloneSection}
  methods: [GET]

section:
  path: '/section/{sectionId}'
  defaults: {_controller: AppBundle:Section:section}
  methods: [GET]

section_modify:
  path: '/modify/section'
  defaults: {_controller: AppBundle:Section:modifyPost}
  methods: [POST]
  
# problem routes
problem_edit:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/edit/{problemId}'
  defaults: 
    _controller: AppBundle:Problem:edit
    problemId: 0
  methods: [GET]

problem_delete:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/delete/{problemId}'
  defaults: {_controller: AppBundle:Problem:delete}
  methods: [GET]

problem_result:
    path: '/result/{submission_id}'
    defaults: {_controller: AppBundle:Problem:result}
    requirements:
        submission_id: '\d+'
        
result_delete:
    path: '/result_delete/{submission_id}'
    defaults: {_controller: AppBundle:Problem:resultDelete}
    requirements:
        submission_id: '\d+'

problem_modify:
    path: 'modify/problem'
    defaults:
        _controller: AppBundle:Problem:modifyPost
    methods: [POST]


# assignment routes
assignment_edit:
  path: '/section/{sectionId}/assignment/edit/{assignmentId}'
  defaults:
    _controller: AppBundle:Assignment:edit
    assignmentId: 0
  methods: [GET]

assignment_delete:
  path: '/section/{sectionId}/assignment/delete/{assignmentId}'
  defaults: {_controller: AppBundle:Assignment:delete}
  methods: [GET]
  
assignment:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/{problemId}'
  defaults:
    _controller: AppBundle:Assignment:assignment
    problemId: 0
  methods: [GET]

assignment_modify:
  path: '/modify/assignment'
  defaults:
    _controller: AppBundle:Assignment:modifyPost
  methods: [POST]

assignment_clearsubs:
  path: '/modify/assignment/clearsubs'
  defaults:
    _controller: AppBundle:Assignment:clearSubmissions
  methods: [POST]

assignment_cleartrials:
  path: '/modify/assignment/cleartrials'
  defaults:
    _controller: AppBundle:Assignment:clearTrials
  methods: [POST]


  
# CONTEST ROUTES
contest_result:
  path: '/contest/{contestId}/round/{roundId}/problem/{problemId}/result/{resultId}'
  defaults:
    _controller: AppBundle:ContestPages:result
  methods: [GET]
  
contest_problem_edit:
  path: '/contest/{contestId}/round/{roundId}/problem/edit/{problemId}'
  defaults:
    _controller: AppBundle:ContestPages:problemEdit
    problemId: 0
  methods: [GET]
  
contest_problem:
  path: '/contest/{contestId}/round/{roundId}/problem/{problemId}'
  defaults:
    _controller: AppBundle:ContestPages:problem
    problemId: 0
  methods: [GET]
  
contest_judging:
  path: '/contest/{contestId}/round/{roundId}/judging'
  defaults:
    _controller: AppBundle:ContestPages:judging
  methods: [GET]
  
contest_edit:
  path: '/contest/edit/{contestId}'
  defaults:
    _controller: AppBundle:ContestPages:contestEdit
    roundId: 0
  methods: [GET]
  
contest_scoreboard:
  path: '/contest/{contestId}/round/{roundId}/anon_scoreboard'
  defaults:
    _controller: AppBundle:ContestPages:scoreboard
  methods: [GET]
  
contest:
  path: '/contest/{contestId}/round/{roundId}'
  defaults:
    _controller: AppBundle:ContestPages:contest
    roundId: 0
  methods: [GET]
   
contest_problem_modify:
  path: '/modify/contest_problem'
  defaults:
    _controller: AppBundle:ContestPost:modifyProblemPost
  methods: [POST]
 
contest_modify:
  path: '/modify/contest'
  defaults:
    _controller: AppBundle:ContestPost:modifyContestPost
  methods: [POST]
  
judging_modify:
  path: '/judging/submission'
  defaults:
    _controller: AppBundle:ContestPost:submissionJudging
  methods: [POST]
  
judging_query:
  path: '/judging/query'
  defaults:
    _controller: AppBundle:ContestPost:postQuestion
  methods: [POST]

judging_scoreboard:
  path: '/judging/scoreboard_freeze'
  defaults:
    _controller: AppBundle:ContestPost:scoreboardFreeze
  methods: [POST]
    
# TRIAL ROUTES
modify_trial:
  path: 'modify/trial'
  defaults:
    _controller: AppBundle:Trial:trialModify
  methods: [POST]    
  
# UPLOAD ROUTES
get_contents:
  path: '/get_contents'
  defaults: { _controller: AppBundle:Upload:getContents}
  methods: [POST]

# temporary route for GUI development
professorsection:
    path: "/professor/section/{userId}/{sectionId}"
    defaults: {_controller: AppBundle:Professorsection:professorsection}


temp_trial_submit:
    path: '/quick_submit/{trialId}'
    defaults:
        _controller: AppBundle:Trial:quick
        trialId: 0
    methods: [POST]

contest_temp_trial_submit:
    path: '/contest_quick_submit/{trialId}'
    defaults:
        _controller: AppBundle:ContestCompilation:contestQuick
        trialId: 0
    methods: [POST]   
    
submit:
    path: '/submit'
    defaults:
        _controller:    AppBundle:Compilation:submit

contest_submit:
    path: '/contest_submit'
    defaults:
        _controller:    AppBundle:ContestCompilation:contestSubmit

generate:
    path: '/generate'
    defaults:
        _controller:    AppBundle:Compilation:generate
    methods: [POST]

# AUTHENTICATION ROUTES
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

user_logout:
    path: '/user/logout'

user_login:
  path: '/user/login'
  defaults: {_controller: AppBundle:Login:index}


chihuahua_spin:
  path: 'spin'
  defaults: {_controller: AppBundle:Hilarious:spin}
