app:
    resource: '@AppBundle/Controller/'
    type: annotation

index: 
    path: "/"
    defaults: {_controller: AppBundle:Default:index}

courses:
    path: "/courses"
    defaults: {_controller: AppBundle:Courses:courses}

assignments:
    path: "/courses/assignments/{course_number}"
    defaults: {_controller: AppBundle:Assignments:assignments}

submit: 
    path: "/courses/assignments/submit/{project_id}"
    defaults: {_controller: AppBundle:Submit:submit}
