index:
  path: '/'
  defaults: {_controller: AppBundle:Default:index}

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

auth0_login:
    path:    /auth0/callback

auth0_logout:
    path: /auth0/logout

account:
  path: '/account/{userId}'
  defaults: {_controller: AppBundle:Default:account}

section:
  path: '/account/{userId}/section/{sectionId}'
  defaults: {_controller: AppBundle:Section:section}

assignment:
  path: '/account/{userId}/section/{sectionId}/assignment/{assignmentId}'
  defaults: {_controller: AppBundle:Assignment:assignment}
