homepage:
    path:   '/'
    defaults:  { _controller: AppBundle:Account:index }


hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

index: 
    path: "/"
    defaults: {_controller: AppBundle:Default:index}

courses:
    path: "/courses"
    defaults: {_controller: AppBundle:Courses:courses}
  
user_login:
  path: '/user/login'
  defaults: {_controller: AppBundle:Default:index}

account:
  path: '/account'
  defaults: {_controller: AppBundle:Account:index}

section:
  path: '/account/{userId}/section/{sectionId}'
  defaults: {_controller: AppBundle:Section:section}

assignment:
  path: '/account/{userId}/section/{sectionId}/assignment/{assignmentId}/problem/{problemId}'
  defaults: {_controller: AppBundle:Assignment:assignment, problemId: 1}
  
submit:
    path: '/compilation/submit/{submission_id}/{filetype_id}/{language_id}/{submitted_filename}'
    defaults: 
        _controller:    AppBundle:Compilation:submit
    requirements:
        submission_id:  '\d+'
        filetype_id:    '\d+'
        language_id:    '\d+'
        
submit_backup:
    path: '/compilation/submit_backup/{problem_id}/{filetype_id}/{language_id}/{submitted_filename}'
    defaults: 
        _controller:    AppBundle:Compilation:submit_backup
    requirements:
        problem_id:  '\d+'
        filetype_id: '\d+'
        language_id: '\d+'

problem:
    path: '/account/{userId}/section/{sectionId}/assignment/{assignmentId}/problem/{problem_id}'
    defaults: {_controller: AppBundle:Compilation:problem, problem_id: 1}
    requirements:
        problem_id: '\d+'



error:
    path: '/compilation/error/{problem_id}'
    defaults: {_controller: AppBundle:Compilation:error, problem_id: 1}
    requirements:
        problem_id: '\d+'

submission_results:
    path: '/compilation/submission_results/{submission_id}'
    defaults: {_controller: AppBundle:Compilation:submission}
    requirements:
        submission_id: '\d+'
        
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    
user_logout:
    path: /user/logout
    
user_login:
  path: '/user/login'
  defaults: {_controller: AppBundle:Default:index}