# HOMEPAGE ROUTES
homepage:
    path:   '/home'
    defaults:  { _controller: AppBundle:Home:home} 
    
alt_homepage:
    path:   '/'
    defaults: { _controller: AppBundle:Home:home} 
    
# MAIN ROUTES

section_new:
  path: '/section/new'
  defaults: {_controller: AppBundle:Section:newSection}

section_edit:
  path: '/section/edit/{sectionId}'
  defaults: {_controller: AppBundle:Section:editSection}

section:
  path: '/section/{sectionId}'
  defaults: {_controller: AppBundle:Section:section}

section_insert:
  path: '/section/insert/{courseId}/{name}/{students}/{semester}/{year}/{start_time}/{end_time}/{is_deleted}/{is_public}'
  defaults: {_controller: AppBundle:Section:insertSection}

section_edit_query:
  path: '/section/edit_query/{sectionId}/{courseId}/{name}/{students}/{semester}/{year}/{start_time}/{end_time}/{is_deleted}/{is_public}'
  defaults: 
    _controller: AppBundle:Section:editQuery



assignment_new:
  path: '/section/{sectionId}/assignment/new'
  defaults: {_controller: AppBundle:Assignment:new}

assignment_edit:
  path: '/section/{sectionId}/assignment/edit/{assignmentId}'
  defaults: {_controller: AppBundle:Assignment:edit}

assignment_insert:
  path: '/section/{sectionId}/assignment/insert/{name}/{description}'
  defaults: {_controller: AppBundle:Assignment:insert}

assignment_edit_query:
  path: '/section/{sectionId}/assignment/edit_query/{assignmentId}/{name}/{description}'
  defaults: {_controller: AppBundle:Assignment:editQuery}

assignment:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/{problemId}'
  defaults:
    _controller: AppBundle:Assignment:assignment
    problemId: 0


problem_new:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/new'
  defaults: {_controller: AppBundle:Problem:new}

problem_edit:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/edit/{problemId}'
  defaults: {_controller: AppBundle:Problem:edit}

problem_result:
    path: '/result/{submission_id}'
    defaults: {_controller: AppBundle:Problem:result}
    requirements:
        submission_id: '\d+'

# SUBMISSION ROUTES
upload:
  path: "/upload/{problem_id}"
  defaults: {_controller: AppBundle:Upload:upload}
  requirements:
    problem_id:     '\d+'

# temporary route for GUI development
professorsection:
    path: "/professor/section/{userId}/{sectionId}"
    defaults: {_controller: AppBundle:Professorsection:professorsection}



submit:
    path: '/submit/{problem_id}/{language_id}/{submitted_filename}/{main_class}/{package_name}'
    defaults:
        _controller:    AppBundle:Compilation:submit
        main_class:     ''
        package_name:   ''
    requirements:
        problem_id:     '\d+'
        language_id:    '\d+'


# AUTHENTICATION ROUTES
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

user_logout:
    path: '/user/logout'

user_login:
  path: '/user/login'
  defaults: {_controller: AppBundle:Login:index}
