submit:
    path: '/compilation/submit/{problem_id}'
    defaults: {_controller: AppBundle:Compilation:submit, problem_id: 1}
    requirements:
        problem_id: '\d+'
   
submission_results:
    path: '/compilation/submission_results/{submission_id}'
    defaults: {_controller: AppBundle:Compilation:submission}
    requirements:
        submission_id: '\d+'