homepage:
    path: '/'
    defaults: {_controller: AppBundle:Default:index}


problem:
    path: '/compilation/problem/{problem_id}'
    defaults: {_controller: AppBundle:Default:problem, problem_id: 1}
    requirements:
        problem_id: '\d+'