# HOMEPAGE ROUTES
homepage:
    path:   '/home'
    defaults:  { _controller: AppBundle:Home:home}

alt_homepage:
    path:   '/'
    defaults: { _controller: AppBundle:Home:home}

# course routes
courses:
  path: '/courses'
  defaults: {_controller: AppBundle:Course:courses}
  methods: [GET]

course_edit:
  path: '/course/edit/{courseId}'
  defaults:
    _controller: AppBundle:Course:editCourse
    courseId: 0
  methods: [GET]

course_delete:
  path: '/course/delete/{courseId}'
  defaults: {_controller: AppBundle:Course:deleteCourse}
  methods: [GET]

course_modify:
  path: '/modify/course'
  defaults: {_controller: AppBundle:Course:modifyPost}
  methods: [POST]

# section routes
section_edit:
  path: '/section/edit/{sectionId}'
  defaults:
    _controller: AppBundle:Section:editSection
    sectionId: 0
  methods: [GET]

section_delete:
  path: '/section/delete/{sectionId}'
  defaults: {_controller: AppBundle:Section:deleteSection}
  methods: [GET]

section:
  path: '/section/{sectionId}'
  defaults: {_controller: AppBundle:Section:section}
  methods: [GET]

section_modify:
  path: '/modify/section'
  defaults: {_controller: AppBundle:Section:modifyPost}
  methods: [POST]

  
# problem routes
problem_edit:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/edit/{problemId}'
  defaults: 
    _controller: AppBundle:Problem:edit
    problemId: 0
  methods: [GET]

problem_delete:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/delete/{problemId}'
  defaults: {_controller: AppBundle:Problem:delete}
  methods: [GET]

problem_result:
    path: '/result/{submission_id}'
    defaults: {_controller: AppBundle:Problem:result}
    requirements:
        submission_id: '\d+'

problem_modify:
    path: 'modify/problem'
    defaults:
        _controller: AppBundle:Problem:modifyPost
    methods: [POST]


# assignment routes
assignment_edit:
  path: '/section/{sectionId}/assignment/edit/{assignmentId}'
  defaults:
    _controller: AppBundle:Assignment:edit
    assignmentId: 0
  methods: [GET]

assignment_delete:
  path: '/section/{sectionId}/assignment/delete/{assignmentId}'
  defaults: {_controller: AppBundle:Assignment:delete}
  methods: [GET]

assignment:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/{problemId}'
  defaults:
    _controller: AppBundle:Assignment:assignment
    problemId: 0
  methods: [GET]

assignment_modify:
  path: '/modify/assignment'
  defaults:
    _controller: AppBundle:Assignment:modifyPost
  methods: [POST]


# UPLOAD ROUTES
get_contents:
    path: '/get_contents'
    defaults: { _controller: AppBundle:Upload:getContents}
    methods: [POST]

# SUBMISSION ROUTES
submission_upload:
  path: "/upload/{problem_id}"
  defaults: {_controller: AppBundle:Upload:submitProblemUpload}
  methods: [POST]
  requirements:
    problem_id:     '\d+'


# temporary route for GUI development
professorsection:
    path: "/professor/section/{userId}/{sectionId}"
    defaults: {_controller: AppBundle:Professorsection:professorsection}

submit:
    path: '/submit'
    defaults:
        _controller:    AppBundle:Compilation:submit
    methods: [POST]

generate:
    path: '/generate'
    defaults:
        _controller:    AppBundle:Compilation:generate
    methods: [POST]

# AUTHENTICATION ROUTES
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

user_logout:
    path: '/user/logout'

user_login:
  path: '/user/login'
  defaults: {_controller: AppBundle:Login:index}
