# HOMEPAGE ROUTES
homepage:
    path:   '/home'
    defaults:  { _controller: AppBundle:Home:home} 
    
alt_homepage:
    path:   '/'
    defaults: { _controller: AppBundle:Home:home} 
    
# section routes
section_delete:
  path: '/section/delete/{sectionId}'
  defaults: {_controller: AppBundle:Section:deleteSection}
  methods: [GET]
  
section_edit:
  path: '/section/edit/{sectionId}'
  defaults: 
    _controller: AppBundle:Section:editSection
    sectionId: 0
  methods: [GET]

section:
  path: '/section/{sectionId}'
  defaults: {_controller: AppBundle:Section:section}
  methods: [GET]

    # section posts
section_modify:
  path: '/modify/section'
  defaults: {_controller: AppBundle:Section:modifyPost}
  methods: [POST]


# assignment routes
assignment_delete:
  path: '/section/{sectionId}/assignment/delete/{assignmentId}'
  defaults: {_controller: AppBundle:Assignment:delete}
  methods: [GET]

assignment_edit:
  path: '/section/{sectionId}/assignment/edit/{assignmentId}'
  defaults: 
    _controller: AppBundle:Assignment:edit
    assignmentId: 0
  methods: [GET]

assignment:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/{problemId}'
  defaults:
    _controller: AppBundle:Assignment:assignment
    problemId: 0
  methods: [GET]
  
  # assignment posts
assignment_modify:
  path: '/modify/assignment'
  defaults:
    _controller: AppBundle:Assignment:modifyPost}
  methods: [POST]


# problem routes
problem_delete:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/delete/{problemId}'
  defaults: {_controller: AppBundle:Problem:delete}
  methods: [GET]

problem_new:
  path: '/section/{sectionId}/assignment/{assignmentId}/new_problem'
  defaults: {_controller: AppBundle:Problem:new}
  
problem_insert:
  path: '/section/{sectionId}/assignment/{assignmentId}/new_problem'
  defaults: {_controller: AppBundle:Problem:insert}

problem_edit:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/edit/{problemId}'
  defaults: {_controller: AppBundle:Problem:edit}

problem_result:
    path: '/result/{submission_id}'
    defaults: {_controller: AppBundle:Problem:result}
    requirements:
        submission_id: '\d+'
        
   
# testcase routes
testcase_new:
  path: '/section/{sectionId}/assignment/{assignmentId}/new_problem'
  defaults: {_controller: AppBundle:TestCase:new}
  
testcase_insert:
  path: '/section/{sectionId}/assignment/{assignmentId}/new_problem'
  defaults: {_controller: AppBundle:TestCase:insert}

testcase_edit:
  path: '/section/{sectionId}/assignment/{assignmentId}/problem/edit/{problemId}'
  defaults: {_controller: AppBundle:TestCase:edit}

testcase_result:
    path: '/result/{submission_id}'
    defaults: {_controller: AppBundle:TestCase:result}

# UPLOAD ROUTES
get_contents:
    path: '/get_contents'
    defaults: { _controller: AppBundle:Upload:getContents}
    methods: [POST]    

# SUBMISSION ROUTES
submission_upload:
  path: "/upload/{problem_id}"
  defaults: {_controller: AppBundle:Upload:submitProblemUpload}
  methods: [POST]
  requirements:
    problem_id:     '\d+'
  

# temporary route for GUI development
professorsection:
    path: "/professor/section/{userId}/{sectionId}"
    defaults: {_controller: AppBundle:Professorsection:professorsection}

submit:
    path: '/submit/{problem_id}/{language_id}/{submitted_filename}/{main_class}/{package_name}'
    defaults:
        _controller:    AppBundle:Compilation:submit
        main_class:     ''
        package_name:   ''
    requirements:
        problem_id:     '\d+'
        language_id:    '\d+'


# AUTHENTICATION ROUTES
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

user_logout:
    path: '/user/logout'

user_login:
  path: '/user/login'
  defaults: {_controller: AppBundle:Login:index}
