# EMILY'S ROUTE
homepage:
    path:   '/'
    defaults:  { _controller: AppBundle:Account:index }
    
# CHRIS'S''S'S'S'S'S'S'SS'S' ROUTES
account:
  path: '/account'
  defaults: {_controller: AppBundle:Account:index}

section:
  path: '/account/{userId}/section/{sectionId}'
  defaults: {_controller: AppBundle:Section:section}

assignment:
  path: '/account/{userId}/section/{sectionId}/assignment/{assignmentId}/problem/{problemId}'
  defaults: {_controller: AppBundle:Problems:problems, problemId: 1}
  
# EMMETT'S ROUTE 
upload:
  path: "/courses/assignments/problems/{project_id}/{problem_id}/upload"
  defaults: {_controller: AppBundle:Upload:upload}
  
  
# TIMOTHY'S ROUTES
submit:
    path: '/compilation/submit/{submission_id}/{filetype_id}/{language_id}/{submitted_filename}'
    defaults: 
        _controller:    AppBundle:Compilation:submit
    requirements:
        submission_id:  '\d+'
        filetype_id:    '\d+'
        language_id:    '\d+'
        
submit_backup:
    path: '/compilation/submit_backup/{problem_id}/{filetype_id}/{language_id}/{submitted_filename}'
    defaults: 
        _controller:    AppBundle:Compilation:submit_backup
    requirements:
        problem_id:  '\d+'
        filetype_id: '\d+'
        language_id: '\d+'

submission_results:
    path: '/compilation/submission_results/{submission_id}'
    defaults: {_controller: AppBundle:Compilation:submission}
    requirements:
        submission_id: '\d+'

# OAUTH'S ROUTES
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    
user_logout:
    path: '/user/logout'

user_login:
  path: '/user/login'
  defaults: {_controller: AppBundle:Default:index}    