
index:
  path: '/'
  defaults: {_controller: AppBundle:Default:index}

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

auth0_login:
    path:    /auth0/callback

auth0_logout:
    path: /auth0/logout

account:
  path: '/account/{userId}'
  defaults: {_controller: AppBundle:Default:account}

section:
  path: '/account/{userId}/section/{sectionId}'
  defaults: {_controller: AppBundle:Section:section}

assignment:
  path: '/account/{userId}/section/{sectionId}/assignment/{assignmentId}'
  defaults: {_controller: AppBundle:Assignment:assignment}

problem:
    path: '/account/{userId}/section/{sectionId}/assignment/{assignmentId}/problem/{problem_id}'
    defaults: {_controller: AppBundle:Compilation:problem, problem_id: 1}
    requirements:
        problem_id: '\d+'

submit:
    path: '/account/{userId}/section/{sectionId}/assignment/{assignmentId/problem/{problem_id}/submit'
    defaults: {_controller: AppBundle:Compilation:submit, problem_id: 1}
    requirements:
        problem_id: '\d+'


error:
    path: '/compilation/error/{problem_id}'
    defaults: {_controller: AppBundle:Compilation:error, problem_id: 1}
    requirements:
        problem_id: '\d+'



submission_results:
    path: '/compilation/submission_results/{submission_id}'
    defaults: {_controller: AppBundle:Compilation:submission}
    requirements:
        submission_id: '\d+'
