; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

	TITLE	c:\Users\ewolf\documents\visual studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UfhvihUvdlouUwlxfnvmghUerhfzoLhgfwrlLCABHUkilqvxghUxlmhlovzkkorxzgrlmBUxlmhlovzkkorxzgrlmBUwvyftUhgwzucOlyq@4B2008FD98C1DD4
;	COMDAT ___@@_PchSym_@00@UfhvihUvdlouUwlxfnvmghUerhfzoLhgfwrlLCABHUkilqvxghUxlmhlovzkkorxzgrlmBUxlmhlovzkkorxzgrlmBUwvyftUhgwzucOlyq@4B2008FD98C1DD4
_BSS	SEGMENT
___@@_PchSym_@00@UfhvihUvdlouUwlxfnvmghUerhfzoLhgfwrlLCABHUkilqvxghUxlmhlovzkkorxzgrlmBUxlmhlovzkkorxzgrlmBUwvyftUhgwzucOlyq@4B2008FD98C1DD4 DD 01H DUP (?)
_BSS	ENDS
END
