
submit:
    path:     /submit
    defaults: { _controller: AppBundle:Submit:submit }

student_submit:
    path:     /studentSubmit
    defaults: { _controller: AppBundle:Submit:studentSubmit }

submit:
    path:     /submit
    defaults: { _controller: AppBundle:Submit:submit }
