clear

echo "Hello! Welcome to the 'interactive' auto-compiler demo, Dr. Gallagher!"
read -n 1 -s -r -p "Press any key to continue..."

echo ""
echo ""
echo "We have a fancy new problem called 'Calculate the Sum' that we would like to solve!"

read -p "Enter an integer to represent the id of your team: " -a team_id
read -p "Enter an integer to represent the id of the problem 'Calculate the Sum': " -a problem_id

echo ""
echo "Great! We have problem 'Calculate the Sum' with problem id $problem_id that team $team_id would like to submit a solution for!"

cp -r problems/111 problems/$problem_id


echo ""
echo "We have input files specified in the problems/$problem_id/input folder."
ls -l problems/$problem_id/input/

echo ""
echo "We have correct output files specified in the problems/$problem_id/output folder."
ls -l problems/$problem_id/output/

echo ""
echo "We wrote our code and uploaded it the website. We will pretend that this code was then put in the test_code directory"
cat test_code/sum.c

read -n 1 -s -r -p "Press any key to continue..."

echo ""
echo ""
echo "We can now create a docker container, copy the files over, run the code in a safe environment, and test the output against the correct output"
echo "Here is the command that we are about to issue:"
echo "./dockercompiler.sh $problem_id $team_id /var/www/dev/tgsmith/Gradel/docker_test/test_code sum.c c false 3 '' gallaghdemo"
echo ""
echo ""
read -n 1 -s -r -p "Press any key to automatically compile and run the code!"

touch temp.file
./dockercompiler.sh $problem_id $team_id /var/www/dev/tgsmith/Gradel/docker_test/test_code sum.c c false 3 "" gallaghdemo > temp.file

echo ""
echo "Done!"
echo "Here is output generated by that command:"
echo "-----------------------------------------"
echo ""
cat temp.file
rm temp.file

echo "-----------------------------------------"
echo ""
echo "The submission is temporarily stored in the submissions/$team_id/$problem_id folder and gives us a copy of the submitted code, the output files generated, and a compiler log (that has nothing in it yet)"
echo ""

echo "Let's take a closer look at what we have."
echo "In the submissions/$team_id/$problem_id/gallaghdemo directory we have the following files."
ls -l submissions/$team_id/$problem_id/gallaghdemo
echo ""
echo "code: stores the submitted code - unzipped"
echo "logs: stores some compiler and running debug output (not used yet)"
echo "output: stores the output for each test case"

echo ""

read -n 1 -s -r -p "Thanks for joining us! Press any key to exit this good demo!"
echo ""
clear
